name: kinsim
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - biopandas=0.2.4=py_0
  - biopython=1.74=py36h516909a_0
  - bleach=3.1.0=py_0
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py36_1
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py36_1000
  - expat=2.2.5=he1b5a44_1003
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - icu=58.2=hf484d3e_1000
  - importlib_metadata=0.18=py36_0
  - ipykernel=5.1.1=py36h5ca1d4c_0
  - ipython=7.6.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.0=py_0
  - jedi=0.14.1=py36_0
  - jinja2=2.10.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.1=py_0
  - jupyter_console=6.0.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyter_highlight_selected_word=0.2.0=py36_1000
  - jupyter_latex_envs=1.4.4=py36_1000
  - jupyter_nbextensions_configurator=0.4.1=py36_0
  - kiwisolver=1.1.0=py36hc9558a2_0
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=10_openblas
  - libopenblas=0.3.6=h6e990d7_5
  - libpng=1.6.37=hed695b0_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - libxslt=1.1.32=hae48121_1003
  - lxml=4.4.0=py36h7ec2d77_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=3.1.1=py36_0
  - matplotlib-base=3.1.1=py36hfd891ef_0
  - mistune=0.8.4=py36h14c3975_1000
  - more-itertools=7.1.0=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - notebook=6.0.0=py36_0
  - numpy=1.16.4=py36h95a1406_0
  - openblas=0.3.6=h6e990d7_5
  - openssl=1.1.1c=h516909a_0
  - packaging=19.0=py_0
  - pandas=0.25.0=py36hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pip=19.2.1=py36_0
  - pluggy=0.12.0=py_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.1=py_0
  - pyqt=5.9.2=py36hcca6a23_0
  - pyrsistent=0.15.3=py36h516909a_0
  - pytest=5.0.1=py36_1
  - python=3.6.7=h357f687_1005
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pyyaml=5.1.1=py36h516909a_0
  - pyzmq=18.0.2=py36h1768529_2
  - qt=5.9.7=h52cfd70_2
  - qtconsole=4.5.2=py_0
  - readline=8.0=hf8c457e_0
  - scipy=1.3.0=py36h921218d_0
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sqlite=3.29.0=hcee41ef_0
  - statsmodels=0.10.1=py36hc1659b7_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1002
  - tornado=6.0.3=py36h516909a_0
  - traitlets=4.3.2=py36_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.4=py36_0
  - widgetsnbextension=3.5.0=py36_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zipp=0.5.1=py_0
  - zlib=1.2.11=h516909a_1005
prefix: /home/dominique/anaconda2/envs/kinsim

